name: timeline_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python>3.7
  - pandas
  - matplotlib
  - jupyterlab>3.0.7
  - numpy
  - langchain
  - pypdf
  - pip:
    - huggingface_hub
    - chromadb
    - tiktoken
    - unstructured